version: "3.4"

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_MESSAGE_MAX_BYTES=2147483647 
      - KAFKA_LOG_SEGMENT_BYTES=5000000
    depends_on:
      - zookeeper
  sql-container:
    container_name: social.portal
    hostname: mssql-db
    image: 'mcr.microsoft.com/mssql/server:latest'
    restart: always
    ports:
      - "1432:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    networks:
      - mydockernetwork
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        sleep 30s
        /docker-entrypoint-initdb.d/init-db.sh
  mongo-container:
    container_name: socialmedia
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - "mongo_data:/data/db"
    networks:
        - mydockernetwork

  # Doesn't work, you should be ashamed of yourself
  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo_gui
  #   environment:
  #       ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #       ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #       ME_CONFIG_MONGODB_URL: mongodb://socialmedia:27018/
  #       ME_CONFIG_MONGODB_PORT: 27018
  #   ports:
  #     - '8081:8081'
  #   networks:
  #     - mydockernetwork
  #   depends_on:
  #     - mongo-container

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
   
networks:
  mydockernetwork:
      name: mydockernetwork

